"""chess_mcts: Python bindings for the C++ MCTS engine.

Loads the compiled `_core` extension (pybind11) and registers the native
DLL directories it depends on (LibTorch, optional TensorRT) on Windows.

Windows Python 3.8+ import uses LOAD_LIBRARY_SEARCH_DEFAULT_DIRS, which
ignores %PATH%; only `os.add_dll_directory` is honored. The paths below
are baked at CMake configure time into `_paths.py` so editable installs
resolve the right LibTorch / TensorRT dirs regardless of the caller's
environment.
"""

import os
import sys

from . import _paths  # generated by CMake configure_file


def _register_dll_dirs() -> None:
    if sys.platform != "win32":
        return
    for d in (_paths.LIBTORCH_LIB, _paths.TENSORRT_BIN):
        if d and os.path.isdir(d):
            try:
                os.add_dll_directory(d)
            except (AttributeError, OSError):
                pass


_register_dll_dirs()

from ._core import *  # noqa: E402,F401,F403
from ._core import (  # noqa: E402,F401  — explicit re-export for IDEs
    SearchEngine,
    GameManager,
    SearchResult,
)

# encode_packed is optional (may not be exposed in older bindings).
try:
    from ._core import encode_packed  # noqa: F401
except ImportError:
    pass
